apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  #pod definition
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: helloworld
          image: nginxdemos/hello