apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    xargon: xargon
spec:
  replicas: 2
  selector:
    matchLabels:
      xargon: xargon
  template:
    metadata:
      name: web-server
      labels:
        xargon: xargon
    spec:
      containers:
        - name: nginx-hello-world
          image: nginxdemos/hello
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-port-example
spec:
  type: NodePort
  selector:
    xargon: xargon
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30149